package entity

type SlaveStatus struct {
	SlaveIOState              string
	MasterHost                string
	MasterUser                string
	MasterPort                string
	ConnectRetry              string
	MasterLogFile             string
	ReadMasterLogPos          string
	RelayLogFile              string
	RelayLogPos               string
	RelayMasterLogFile        string
	SlaveIORunning            string
	SlaveSQLRunning           string
	ReplicateDoDB             string
	ReplicateIgnoreDB         string
	ReplicateDoTable          string
	ReplicateIgnoreTable      string
	ReplicateWildDoTable      string
	ReplicateWildIgnoreTable  string
	LastErrno                 string
	LastError                 string
	SkipCounter               string
	ExecMasterLogPos          string
	RelayLogSpace             string
	UntilCondition            string
	UntilLogFile              string
	UntilLogPos               string
	MasterSSLAllowed          string
	MasterSSLCAFile           string
	MasterSSLCAPath           string
	MasterSSLCert             string
	MasterSSLCipher           string
	MasterSSLKey              string
	SecondsBehindMaster       string
	MasterSSLVerifyServerCert string
	LastIOErrno               string
	LastIOError               string
	LastSQLErrno              string
	LastSQLError              string
	ReplicateIgnoreServerIds  string
	MasterServerId            string
	MasterUUID                string
	MasterInfoFile            string
	SQLDelay                  string
	SQLRemainingDelay         string
	SlaveSQLRunningState      string
	MasterRetryCount          string
	MasterBind                string
	LastIOErrorTimestamp      string
	LastSQLErrorTimestamp     string
	MasterSSLCrl              string
	MasterSSLCrlpath          string
	RetrievedGtidSet          string
	ExecutedGtidSet           string
	AutoPosition              string
	ReplicateRewriteDB        string
	ChannelName               string
	MasterTLSVersion          string
	Masterpublickeypath       string
	Getmasterpublickey        string
	NetworkNamespace          string
}
